### ISSUE TITLE
Terms of Use are unclear about whether it's open source or not

### ISSUE THREAD

**Issue by rory** [facebookmicrosites/Open-Mapping-At-Facebook#2]
The [copyright licence for this project](https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/blob/master/LICENSE.md) is MIT, an open source licence.

The [mapwith.ai Terms of Use](https://mapwith.ai/doc/license/MapWithAILicense.pdf) also say "You may use any data or information that the Services make available to you(the “Services Data”)under the terms of the MIT license (https://opensource.org/licenses/MIT)", but then later go on to say:

> You may not access or use, or attempt to access or use, the Services to take any action that could ...  For example, and without limitation, you may not
>
> attempt to decipher, decompile, disassemble, or reverse-engineer any of the software comprising or in any way making up a part of the Service;

So, can I "decompile" RapID or not?

**Comment by gaoxm** [comment]
Thanks for submitting the first issue @rory ! The RapiD source code is available at https://github.com/facebookincubator/RapiD. We'll add a link to the website to make it more noticeable and less confusing.

**Comment by gaoxm** [comment]
RapiD repo link added to mapwith.ai website

**Comment by rory** [comment]
The [mapwith.ai website terms of use](https://mapwith.ai/doc/license/MapWithAILicense.pdf) still prohibit reverse engineering, and decompilation.

> attempt to decipher, decompile, disassemble, or reverse-engineer any of the software comprising or in any way making up a part of the Service;

I know this is legal stuff and not easy to change. But c'mon folks!

**Comment by gaoxm** [comment]
Hi Rory,

Let me clarify the license coverages on different components of Map With AI:

(1) The source code of RapiD is published on github and that's available under the terms of the ISC license. There's nothing to decompile there anyway since its provided in source code.

(2) The AI-generated roads that are made available through RapiD are available via the MIT license. There is nothing to decompile there either because they are provided in human-readable XML format (although mostly consumed through map editing activities in RapiD).

(3) Finally, there is the provision of the **mapwith.ai** website itself, which is covered by the [mapwith.ai website terms of use](https://mapwith.ai/doc/license/MapWithAILicense.pdf). Similar to other public services like github, we are providing the service by hosting **mapwith.ai** and the terms apply only to our hosting and provisioning of the website.

I hope that answers your question or concern :).
